### ISSUE TITLE
Crontab not working correctly via run.py

### ISSUE THREAD

**Issue by alexandzors** [alexandzors/covid-19#2]
Python-Crontab seems to not be working correctly for Docker version.

Example Error:

```
File "./run.py", line 13, in <module>
job = cron.new(command='python covid19.py', comment='Covid19 Script')
File "/usr/local/lib/python3.8/site-packages/crontab.py", line 416, in new
raise ValueError("User is required for system crontabs.")
ValueError: User is required for system crontabs.
```

**Comment by FortDigital** [comment]
Not that it helps but i see the same behaviour when running it on my Pi or my windows device. Is there a particular reason for using user=False rather than user=True? (Not used Crontab much sorry!)

**Comment by alexandzors** [comment]
I was reading the documentation for python-crontab and thought that's how you did it if you wanted to run it as system/root. I'm fairly new to python/crontab so I'll have to look at it further and see if I just missed something.

**Comment by alexandzors** [comment]
Ok so fixed the cron job but cant seem to get the container to stay running now.

**Comment by alexandzors** [comment]
@FortDigital hey, can you pull the latest image and give it a try? I think I might have fixed it.
